apiVersion: apps/v1
kind: Deployment
metadata:
    name: carrental-deployment
    labels:
      app: carrental
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carrental
  template:
    metadata:
      labels:
        app: carrental
    spec:
      containers:
      - name: carrental
        image: tiagomadeiradock/railscarrentalsapi:1.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: carrental-secrets
              key: rails-master-key
        - name: DEVISE_JWT_SECRET_KEY 
          valueFrom:
            secretKeyRef:
              name: carrental-secrets
              key: devise-jwt-secret-key
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credencials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credencials
              key: password
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: carrental-configmap
              key: database_url
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: carrental-internal-service
spec:
  selector:
    app: carrental
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
